language: android
jdk: oraclejdk8
sudo: required

before_install:
 - chmod +x gradlew
env:
  global:
    - ANDROID_API_LEVEL=25
    - EMULATOR_API_LEVEL=19
    - ANDROID_BUILD_TOOLS_VERSION=25.0.2
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TRAVIS=1
android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    # Specify both versions to resolve issue with missing image from google repository
    - android-$ANDROID_API_LEVEL
    - android-$EMULATOR_API_LEVEL
    - extra-android-support
    - extra-android-m2repository
    - extra-android-google_play_services
    - extra-google-m2repository

script:
- ./gradlew jacocoTestReport coveralls
